# Google Cloud Build configuration for CI/CD
# Automatically builds and deploys on git push

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/epic-games-notifier:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/epic-games-notifier:latest'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/epic-games-notifier:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/epic-games-notifier:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'epic-games-notifier'
      - '--image=gcr.io/$PROJECT_ID/epic-games-notifier:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--set-env-vars=EPIC_LOCALE=en-US,EPIC_COUNTRY=US'
      - '--set-secrets=DISCORD_WEBHOOK_URL=discord-webhook-url:latest'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/epic-games-notifier:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/epic-games-notifier:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for entire build
timeout: '1200s'
